<h1><center>Практическая работа №1</center></h1>

<h2><center>Разведочный анализ</center></h2>

<b>Цель:</b> Провести разведочный анализ данных по датасету наблюдений диких кошачьих (GBIF).

<b>Задание на практическую работу:</b>

<ul>
<li>Загрузка датасета;</li>
<li>Просмотр и исследование датасета;</li>
<li>Обработка датасета:</li>
    <ul>
        <li>Удаление хотя бы одного признака;</li>
        <li>Замена и удаление значений;</li>
        <li>Отсортировать значения в датафрейме по указанному столбцу;</li>
        <li>Убрать дубликаты в датафрейме;</li>
    </ul>
<li>Выбрать один признак (категориальный) в качестве целевой переменной и обосновать данный выбор;</li>
<li>Написать заключение по проведенному исследованию;</li>
<li>Сохранить датасет.</li>
<li>На основе собственного выбранного датасета проведен разведочный анализ со всеми этапами.</li>
<li>Отчет оформлен информативно и полно.</li>
</ul>

Для практической работы были использованы следующие библиотеки:

In [2]:
import pandas as pd
import numpy as np

Перед началом анализа подключаются две библиотеки.

<b>pandas</b> - основной инструмент для табличных данных в Python. DataFrame можно представить как «умный» аналог Excel-таблицы: у каждой строки есть индекс, у каждого столбца - имя и тип. Через pandas удобно читать файлы, фильтровать, агрегировать, менять структуру и сохранять результат.

<b>NumPy</b> лежит в основе числовых операций pandas. Именно через него считаются средние, медианы, стандартные отклонения и обрабатываются пропуски (<code>NaN</code>). В явном виде NumPy в этой работе почти не вызывается, но без него pandas работать не сможет.

<h2>1. Загрузка датасета</h2>

In [3]:
path = "pw1_data_set.csv"

Путь к файлу сохраняется в переменную <code>path</code>.

Исходный CSV <code>pw1_data_set.csv</code> - выборка наблюдений диких кошачьих из международной базы GBIF (400+ строк). В каждой строке: идентификатор записи, обычное и латинское название вида, страна, координаты, год и месяц, способ регистрации наблюдения, число особей и лицензия на данные.

In [5]:
df = pd.read_csv(path)

<code>pd.read_csv()</code> - стандартный способ загрузить таблицу из CSV.

Алгоритм работы метода:
<ol>
<li>открывается текстовый файл;</li>
<li>первая строка воспринимается как заголовки столбцов;</li>
<li>для каждого столбца пытается выявляется тип;</li>
<li>пустые ячейки конвертируются в значение <code>NaN</code>;</li>
<li>всёсобирается в объект <code>DataFrame</code> и возвращается методом.</li>
</ol>

Результат сохраняется в переменную <code>df</code> - в последующем эта переменная использвалась для доступа к данным.

<h2>2. Просмотр и исследование дата-сета</h2>

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 424 entries, 0 to 423
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gbif_id                   424 non-null    int64
 1   common_name               424 non-null    str
 2   scientific_name           424 non-null    str
 3   country_code              424 non-null    str
 4   latitude                  424 non-null    float64
 5   longitude                 424 non-null    float64
 6   coordinate_uncertainty_m  71 non-null     float64
 7   year                      424 non-null    int64
 8   month                     397 non-null    float64
 9   event_date                424 non-null    str
 10  basis_of_record           424 non-null    str
 11  individual_count          173 non-null    float64
 12  dataset_key               424 non-null    str
 13  license                   424 non-null    str
dtypes: float64(5), int64(2), str(7)
memory usage: 87.7 KB

<code>df.info()</code> - команда, выводящая основную информацию о дата-сете в виде списка-таблици.

Командой было выведено:
<ul>
<li>класс объекта и диапазон индексов;</li>
<li>список всех столбцов с числом заполненных ячеек и типом данных;</li>
<li>сколько памяти занимает таблица.</li>
</ul>

По <code>Non-Null Count</code> были выявлены пропуски: если число меньше общего количества строк — в столбце есть пустые значения. В данном дата-сете полностью заполнены идентификаторы, названия видов, страна, координаты, год и тип записи. Пробелы есть в точности координат, месяце и числе особей.

In [7]:
df.head()

,gbif_id,common_name,scientific_name,country_code,latitude,longitude,coordinate_uncertainty_m,year,month,event_date,basis_of_record,individual_count,dataset_key,license
0,5995618229,Eurasian Lynx,Lynx lynx,NO,63.319014,10.415158,NaN,2013,1.0,2013-01-01,HUMAN_OBSERVATION,NaN,56fb17ca-adb2-4d82-81e1-f14803db0418,CC_BY_4_0
1,5995625033,Eurasian Lynx,Lynx lynx,NO,62.668937,9.515745,NaN,2014,1.0,2014-01-01,HUMAN_OBSERVATION,NaN,56fb17ca-adb2-4d82-81e1-f14803db0418,CC_BY_4_0
2,5995618142,Eurasian Lynx,Lynx lynx,NO,63.251434,10.466199,NaN,2012,4.0,2012-04-22,HUMAN_OBSERVATION,NaN,56fb17ca-adb2-4d82-81e1-f14803db0418,CC_BY_4_0
3,5995624922,Eurasian Lynx,Lynx lynx,NO,63.306717,10.404451,NaN,2013,4.0,2013-04-19,HUMAN_OBSERVATION,NaN,56fb17ca-adb2-4d82-81e1-f14803db0418,CC_BY_4_0
4,5995624921,Eurasian Lynx,Lynx lynx,NO,62.710837,10.153450,NaN,2009,5.0,2009-05-31,HUMAN_OBSERVATION,NaN,56fb17ca-adb2-4d82-81e1-f14803db0418,CC_BY_4_0

<code>df.head()</code> - команда, которая по умолчанию выводит первые пять строк дата-сета. Это быстрый способ первичного осмотра столбцов и строк: какие значения реально лежат в ячейках, как выглядят пропуски, не съехали ли заголовки.

В начале файла идут наблюдения евразийской рыси из Норвегии — типичный пример человеческих наблюдений с координатами, но без указания точности и числа особей.

In [8]:
df.tail()

,gbif_id,common_name,scientific_name,country_code,latitude,longitude,coordinate_uncertainty_m,year,month,event_date,basis_of_record,individual_count,dataset_key,license
419,6420896442,Ocelot,Leopardus pardalis,CO,9.530558,-73.460493,NaN,2025,4.0,2025-04-16,MACHINE_OBSERVATION,1.0,ae517055-456d-432b-a317-9df20d080803,CC_BY_NC_4_0
420,6420904691,Ocelot,Leopardus pardalis,CO,9.604610,-73.520380,NaN,2025,9.0,2025-09-26,MACHINE_OBSERVATION,1.0,ae517055-456d-432b-a317-9df20d080803,CC_BY_NC_4_0
421,1829117893,Ocelot,Leopardus pardalis,CO,11.029472,-73.614806,NaN,2015,12.0,2015-12-02,MACHINE_OBSERVATION,NaN,31da52cd-6114-439d-be0a-700bf52de8f3,CC_BY_NC_4_0
422,1829121007,Jaguarundi,Puma yagouaroundi,CO,10.245278,-73.764444,NaN,2015,NaN,2015-08-25,HUMAN_OBSERVATION,NaN,31da52cd-6114-439d-be0a-700bf52de8f3,CC_BY_NC_4_0
423,1829118322,Ocelot,Leopardus pardalis,CO,9.929111,-75.168111,NaN,2015,8.0,2015-08-07,HUMAN_OBSERVATION,NaN,31da52cd-6114-439d-be0a-700bf52de8f3,CC_BY_NC_4_0

<code>df.tail()</code> - команда, противоположность head(), выводит последние записи в дата-сете. Сравнивая начало и конец, можно заметить, что в выборке есть и другие виды (оцелот, ягуарунди?), и другие страны. Это подтверждает, что дата-сет не сводится к одному региону или одному виду и скорее всего не заполнен одинаковыми копиями данных.

In [9]:
print(df.shape)
print('Количество строк:', df.shape[0])
print('Количество столбцов:', df.shape[1])

(424, 14)
Количество строк: 424
Количество столбцов: 14

Атрибут <code>df.shape</code> возвращает пару чисел: <code>(число строк, число столбцов)</code>.

Через индексацию удобно брать по отдельности:
<ul>
<li><code>df.shape[0]</code> — сколько наблюдений;</li>
<li><code>df.shape[1]</code> — сколько признаков.</li>
</ul>

In [10]:
df.columns.tolist()

['gbif_id',
 'common_name',
 'scientific_name',
 'country_code',
 'latitude',
 'longitude',
 'coordinate_uncertainty_m',
 'year',
 'month',
 'event_date',
 'basis_of_record',
 'individual_count',
 'dataset_key',
 'license']

<code>df.columns</code> хранит имена столбцов. Вызов <code>.tolist()</code> превращает их в обычный Python-список — так проще читать и копировать имена.

Описание признаков данного дата-сета:
<ul>
<li><code>gbif_id</code> - уникальный номер записи в GBIF;</li>
<li><code>common_name</code> / <code>scientific_name</code> - обычное и латинское название вида;</li>
<li><code>country_code</code> - двухбуквенный код страны (ISO 3166);</li>
<li><code>latitude</code>, <code>longitude</code> - широта и долгота;</li>
<li><code>coordinate_uncertainty_m</code> - погрешность координат в метрах;</li>
<li><code>year</code>, <code>month</code>, <code>event_date</code> - время наблюдения;</li>
<li><code>basis_of_record</code> - как получена запись (человек, камера/датчик, музейный образец);</li>
<li><code>individual_count</code> - сколько особей отмечено;</li>
<li><code>dataset_key</code> - UUID исходного набора в GBIF;</li>
<li><code>license</code> - условия использования данных.</li>
</ul>

In [11]:
df.dtypes

gbif_id                       int64
common_name                     str
scientific_name                 str
country_code                    str
latitude                    float64
longitude                   float64
coordinate_uncertainty_m    float64
year                          int64
month                       float64
event_date                      str
basis_of_record                 str
individual_count            float64
dataset_key                     str
license                         str
dtype: object

<code>df.dtypes</code> - атрибут, который показывает тип каждого столбца. Тип определяет, какие операции допустимы:
<ul>
<li>целые и вещественные (<code>int64</code>, <code>float64</code>) — арифметика, сортировка, статистики;</li>
<li>строки (<code>str</code> / <code>object</code>) — частотный анализ, группировка, замена категорий.</li>
</ul>

в данный момент <code>event_date</code> хранится как текст. Если понадобятся расчёты с датами, столбец нужно будет перевести через <code>pd.to_datetime()</code>.

In [12]:
df.describe()

,gbif_id,latitude,longitude,coordinate_uncertainty_m,year,month,individual_count
count,4.240000e+02,424.000000,424.000000,71.000000,424.000000,397.000000,173.000000
mean,3.950313e+09,26.520265,-5.547481,2859.183099,2015.537736,6.070529,1.219653
std,1.152312e+09,21.479584,59.540340,3788.904068,6.355392,2.972103,0.608339
min,1.722967e+08,-35.390000,-123.158920,2.000000,2000.000000,1.000000,1.000000
25%,3.311192e+09,11.188193,-71.362805,7.500000,2012.000000,4.000000,1.000000
50%,3.941208e+09,35.302736,1.174530,60.000000,2015.000000,5.000000,1.000000
75%,4.064338e+09,42.909002,2.836339,5937.000000,2020.000000,9.000000,1.000000
max,6.496953e+09,64.931074,129.238000,10000.000000,2025.000000,12.000000,4.000000

<code>df.describe()</code>- метод, который без параметров считает базовые статистики только по числовым столбцам:
<ul>
<li><code>count</code> - сколько значений не пустые;</li>
<li><code>mean</code> и <code>std</code> - среднее значение и стандартное отклонение:;</li>
<li><code>min</code> / <code>max</code> - крайние минимальные и максимальные значения;</li>
<li>квартили <code>25%</code>, <code>50%</code>, <code>75%</code>.</li>
</ul>

по выявленным данным наблюдения ведутся с 2000 по 2025 год, координаты покрывают оба полушария, а неопределённость места может доходить до 10 км. Число особей в типичном случае равно единице.

In [13]:
df.describe(include='str')

,common_name,scientific_name,country_code,event_date,basis_of_record,dataset_key,license
count,424,424,424,424,424,424,424
unique,17,17,20,281,3,27,3
top,European Wildcat,Felis silvestris,FR,2015-05-23,HUMAN_OBSERVATION,745cabaf-11a2-44bf-bc34-dd5a8044eb69,CC_BY_4_0
freq,138,138,129,21,311,115,323

Если передать параметр <code>include='str'</code>, <code>describe</code> работает по текстовым столбцам:
<ul>
<li><code>unique</code> - сколько разных категорий;</li>
<li><code>top</code> - самая частая категория;</li>
<li><code>freq</code> - как часто она встречается.</li>
</ul>

был найден доминирующий вид, страна-лидер, преобладающий способ регистрации и типичную лицензию.

In [14]:
df.isna().sum()

gbif_id                       0
common_name                   0
scientific_name               0
country_code                  0
latitude                      0
longitude                     0
coordinate_uncertainty_m    353
year                          0
month                        27
event_date                    0
basis_of_record               0
individual_count            251
dataset_key                   0
license                       0
dtype: int64

Цепочка <code>df.isna().sum()</code> — удобный способ посчитать пропуски.

<code>isna()</code>служит для поиска пропущенных и пустых значений (NaN, None, NaT), возвращая логическую маску (True / False) той же формы, что и исходный объект. <code>True</code> там, где значение отсутствует. Сумма по столбцу даёт количество пустых ячеек.

В этой выборке пустые значения сосредоточены в трёх местах:
<ul>
<li><code>coordinate_uncertainty_m</code> — чаще всего точность не указана;</li>
<li><code>individual_count</code> — число особей примерно в половине случаев пустое;</li>
<li><code>month</code> — месяц отсутствует примерно в двух десятках строк.</li>
</ul>
Остальные поля заполнены полностью.

In [15]:
df.nunique()

gbif_id                     424
common_name                  17
scientific_name              17
country_code                 20
latitude                    373
longitude                   373
coordinate_uncertainty_m     12
year                         26
month                        12
event_date                  281
basis_of_record               3
individual_count              4
dataset_key                  27
license                       3
dtype: int64

<code>df.nunique()</code> - метод, который выводит число скольких различных значений встречается в каждом столбце.

По этому числу удобно отличать:
<ul>
<li>идентификаторы ( столько же уникальных значений, сколько строк) — например <code>gbif_id</code>;</li>
<li>категории с небольшим числом уровней — <code>basis_of_record</code>, <code>license</code>, <code>month</code>;</li>
<li>числовые величины с широким диапазоном — координаты, год.</li>
</ul>

In [16]:
print('Обычное название вида (common_name):')
print(df['common_name'].value_counts())
print()
print('Код страны (country_code):')
print(df['country_code'].value_counts())
print()
print('Тип записи (basis_of_record):')
print(df['basis_of_record'].value_counts())
print()
print('Лицензия (license):')
print(df['license'].value_counts())
print()
print('Год наблюдения (year):')
print(df['year'].value_counts().sort_index())

Обычное название вида (common_name):
common_name
European Wildcat        138
Lion                     77
Ocelot                   59
Eurasian Lynx            36
Mainland Leopard Cat     35
Cougar                   19
Bobcat                   19
Cheetah                  12
Jaguarundi                9
Caracal                   5
Snow Leopard              4
Jaguar                    3
Margay                    3
Tiger                     2
Jungle Cat                1
Canada Lynx               1
Clouded Leopard           1
Name: count, dtype: int64

Код страны (country_code):
country_code
FR    129
CO     74
BJ     74
KR     35
MX     27
ZA     20
NO     13
ES     11
FI     10
KZ      7
US      6
AR      4
IN      3
UZ      3
MN      3
BR      1
DE      1
UA      1
CR      1
GT      1
Name: count, dtype: int64

Тип записи (basis_of_record):
basis_of_record
HUMAN_OBSERVATION      311
MATERIAL_SAMPLE         66
MACHINE_OBSERVATION     47
Name: count, dtype: int64

Лицензия (license):
license
CC_BY_4_0       323
CC0_1_0          58
CC_BY_NC_4_0     43
Name: count, dtype: int64

Год наблюдения (year):
year
2000     7
2001     5
2002     7
2003     7
2004     6
2005     6
2006     2
2007     2
2008    27
2009    10
2010    11
2011    12
2012    10
2013    13
2014    18
2015    86
2016    13
2017    13
2018    13
2019    24
2020    41
2021     7
2022    19
2023    11
2024    18
2025    36
Name: count, dtype: int64

<code>value_counts()</code> - метод, который строит частотную таблицу по одному столбцу: категория → сколько раз она встретилась. Это один из первых шагов разведочного анализа категориальных признаков.

Краткие выводы по данной выборке:
<ul>
<li>по видам лидирует European Wildcat, затем Lion и Ocelot;</li>
<li>больше всего записей из Франции, Колумбии и Бенина;</li>
<li>способ регистрации в основном человеческий (<code>HUMAN_OBSERVATION</code>);</li>
<li>лицензия чаще всего <code>CC_BY_4_0</code>;</li>
<li>по годам данные распределены неравномерно, с заметным пиком около 2015 года.</li>
</ul>

In [17]:
print('Полных дубликатов строк:', df.duplicated().sum())
print('Повторов gbif_id:', df.duplicated(subset=['gbif_id']).sum())
print('Записей без указания числа особей:', df['individual_count'].isna().sum())
print('Записей без неопределённости координат:', df['coordinate_uncertainty_m'].isna().sum())

Полных дубликатов строк: 0
Повторов gbif_id: 0
Записей без указания числа особей: 251
Записей без неопределённости координат: 353

<code>df.duplicated()</code> - метод, который помечает строки, которые полностью совпадают с уже встреченной ранее. Сумма по этой маске - число полных дубликатов. 

Параметр <code>subset=['gbif_id']</code> указывает проверку одного столбца: ищем повторы идентификатора, даже если остальные поля чуть отличаются.

В исходном файле полных дубликатов и повторов <code>gbif_id</code> нет. Зато много пропусков в точности координат и числе особей.

<h2>3. Обработка датасета</h2>

<h3>3.1. Удаление признака</h3>

In [18]:
print('Уникальных значений dataset_key:', df['dataset_key'].nunique())
print('Примеры dataset_key:', df['dataset_key'].unique()[:3].tolist())
df = df.drop(columns=['dataset_key'])
print('Столбцы после удаления:')
print(df.columns.tolist())
print('Размер таблицы:', df.shape)

Уникальных значений dataset_key: 27
Примеры dataset_key: ['56fb17ca-adb2-4d82-81e1-f14803db0418', 'd8cd16ba-bb74-4420-821e-083f2bac17c2', 'a4d53b24-d61b-4ee5-addd-8b42d54a913f']
Столбцы после удаления:
['gbif_id', 'common_name', 'scientific_name', 'country_code', 'latitude', 'longitude', 'coordinate_uncertainty_m', 'year', 'month', 'event_date', 'basis_of_record', 'individual_count', 'license']
Размер таблицы: (424, 13)

<code>df.drop(columns=[...])</code> убирает указанные столбцы. Важно присвоить результат обратно в <code>df</code> (или использовать <code>inplace=True</code>), иначе исходная таблица не изменится.

Удалён <code>dataset_key</code> - это технический UUID исходного набора данных внутри GBIF. Он не описывает ни вид, ни место, ни время наблюдения и не несёт пользы ни для описательной статистики, ни для будущей модели. После удаления остаётся 13 признаков.

<h3>3.2. Замена и удаление значений</h3>

In [19]:
print('Пропуски до замены:')
print(df[['month', 'individual_count', 'coordinate_uncertainty_m']].isna().sum())

df['month'] = df['month'].fillna(0)  # 0 = месяц не указан
df['individual_count'] = df['individual_count'].fillna(1)  # по умолчанию 1 особь - логично если наблюдение было, значит была хотя бы 1 особь
df['coordinate_uncertainty_m'] = df['coordinate_uncertainty_m'].fillna(-1)  # -1 = неизвестно


df['month'] = df['month'].astype(int)
df['individual_count'] = df['individual_count'].astype(int)

print()
print('Пропуски после замены:')
print(df[['month', 'individual_count', 'coordinate_uncertainty_m']].isna().sum())
print()
print('Значения month после замены (0 = не указан):')
print(df['month'].value_counts().sort_index())

Пропуски до замены:
month                        27
individual_count            251
coordinate_uncertainty_m    353
dtype: int64

Пропуски после замены:
month                       0
individual_count            0
coordinate_uncertainty_m    0
dtype: int64

Значения month после замены (0 = не указан):
month
0      27
1      19
2      19
3      51
4      29
5     106
6      21
7      14
8      26
9      43
10     37
11     19
12     13
Name: count, dtype: int64

На этом шаге ликвидируются пропуски методом <code>fillna</code>.

Логика замен:
<ul>
<li><code>month</code> → 0 — «месяц не указан» (0 не пересекается с реальными 1–12);</li>
<li><code>individual_count</code> → 1 - в большинстве наблюдений отмечается одна особь, и логически если было наблюдение - был минимум 1 объект наблюдения;</li>
<li><code>coordinate_uncertainty_m</code> → −1 - «точность неизвестна» (отрицательное число не путается с реальной погрешностью ≥ 0).</li>
</ul>

Удалять все строки с пропусками было бы неверно: потерялась бы значительная доля данных. Замена сохраняет наблюдения и явно помечает отсутствие информации. После заполнения <code>month</code> и <code>individual_count</code> приведены к целому типу через <code>astype(int)</code>.

In [20]:
rows_before = df.shape[0]

mask_weak = (df['coordinate_uncertainty_m'] > 5000) & (df['month'] == 0)
print('Строк с большой неопределённостью и без месяца:', mask_weak.sum())

df = df.loc[~mask_weak].copy()
df = df.reset_index(drop=True)

print('Строк до удаления:', rows_before)
print('Строк после удаления:', df.shape[0])
print('Удалено строк:', rows_before - df.shape[0])

Строк с большой неопределённостью и без месяца: 10
Строк до удаления: 424
Строк после удаления: 414
Удалено строк: 10

Часть строк можно удалить как малоинформативные.

Строится булева маска: неопределённость координат больше 5000 м <b>и</b> месяц не указан. Такие записи одновременно «размыты» в пространстве и во времени.

Оператор <code>~</code> инвертирует маску. <code>df.loc[~mask]</code> оставляет только «хорошие» строки. <code>.copy()</code> создаёт независимую копию (чтобы не словить предупреждения о SettingWithCopy). <code>reset_index(drop=True)</code> заново нумерует строки с нуля.

Таким образом наблюдения очищаются от неинформативных записей.

<h3>3.3. Сортировка значений по столбцу</h3>

In [21]:
df = df.sort_values(by=['year', 'month'], ascending=[False, False])
df = df.reset_index(drop=True)
df.head(10)

,gbif_id,common_name,scientific_name,country_code,latitude,longitude,coordinate_uncertainty_m,year,month,event_date,basis_of_record,individual_count,license
0,5890685425,Cougar,Puma concolor,CO,5.263247,-71.363765,2.0,2025,10,2025-10-04,MACHINE_OBSERVATION,1,CC_BY_4_0
1,5890685431,Cougar,Puma concolor,CO,5.266473,-71.364107,2.0,2025,10,2025-10-05,MACHINE_OBSERVATION,1,CC_BY_4_0
2,5890686142,Ocelot,Leopardus pardalis,CO,5.274290,-71.439790,2.0,2025,10,2025-10-09,MACHINE_OBSERVATION,1,CC_BY_4_0
3,5890686813,Ocelot,Leopardus pardalis,CO,5.258392,-71.364642,2.0,2025,10,2025-10-05,MACHINE_OBSERVATION,1,CC_BY_4_0
4,5890685430,Ocelot,Leopardus pardalis,CO,5.277341,-71.371847,2.0,2025,10,2025-10-05,MACHINE_OBSERVATION,2,CC_BY_4_0
5,5890685455,Ocelot,Leopardus pardalis,CO,5.276208,-71.373883,2.0,2025,10,2025-10-05,MACHINE_OBSERVATION,2,CC_BY_4_0
6,5890686814,Cougar,Puma concolor,CO,5.258392,-71.364642,2.0,2025,10,2025-10-05,MACHINE_OBSERVATION,1,CC_BY_4_0
7,5890685418,Ocelot,Leopardus pardalis,CO,5.276362,-71.372267,2.0,2025,10,2025-10-05,MACHINE_OBSERVATION,2,CC_BY_4_0
8,5890685434,Ocelot,Leopardus pardalis,CO,5.266473,-71.364107,2.0,2025,10,2025-10-05,MACHINE_OBSERVATION,1,CC_BY_4_0
9,5890685462,Ocelot,Leopardus pardalis,CO,5.276275,-71.374753,2.0,2025,10,2025-10-05,MACHINE_OBSERVATION,1,CC_BY_4_0

<code>sort_values</code> упорядочивает строки по одному или нескольким столбцам.

Здесь сортировка идёт по паре <code>year</code>, <code>month</code> в порядке убывания: сначала самые свежие годы, внутри года — более поздние месяцы. После сортировки индекс «ломается», поэтому его сбрасывают через <code>reset_index(drop=True)</code>.

<code>head(10)</code> показывает десять самых новых записей — удобно для быстрой проверки, что порядок действительно изменился.

<h3>3.4. Удаление дубликатов</h3>

In [22]:
print('Строк до удаления дубликатов:', df.shape[0])
print('Полных дубликатов:', df.duplicated().sum())
print('Повторов gbif_id:', df.duplicated(subset=['gbif_id']).sum())

df = df.drop_duplicates()
df = df.drop_duplicates(subset=['gbif_id'], keep='first')
df = df.reset_index(drop=True)

print('Строк после удаления дубликатов:', df.shape[0])

Строк до удаления дубликатов: 414
Полных дубликатов: 0
Повторов gbif_id: 0
Строк после удаления дубликатов: 414

<code>drop_duplicates()</code> удаляет повторяющиеся строки.

Без аргументов дубликатом считается полное совпадение всех столбцов. С <code>subset=['gbif_id']</code> достаточно совпадения идентификатора. Параметр <code>keep='first'</code> оставляет первое вхождение и отбрасывает остальные.

В текущей выборке повторов не оказалось.

In [23]:
print('Итоговый размер очищенной таблицы:', df.shape)
print()
print(df.info())
print()
df.head()

Итоговый размер очищенной таблицы: (414, 13)

<class 'pandas.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gbif_id                   414 non-null    int64
 1   common_name               414 non-null    str
 2   scientific_name           414 non-null    str
 3   country_code              414 non-null    str
 4   latitude                  414 non-null    float64
 5   longitude                 414 non-null    float64
 6   coordinate_uncertainty_m  414 non-null    float64
 7   year                      414 non-null    int64
 8   month                     414 non-null    int64
 9   event_date                414 non-null    str
 10  basis_of_record           414 non-null    str
 11  individual_count          414 non-null    int64
 12  license                   414 non-null    str
dtypes: float64(3), int64(4), str(6)
memory usage: 68.3 KB
None

,gbif_id,common_name,scientific_name,country_code,latitude,longitude,coordinate_uncertainty_m,year,month,event_date,basis_of_record,individual_count,license
0,5890685425,Cougar,Puma concolor,CO,5.263247,-71.363765,2.0,2025,10,2025-10-04,MACHINE_OBSERVATION,1,CC_BY_4_0
1,5890685431,Cougar,Puma concolor,CO,5.266473,-71.364107,2.0,2025,10,2025-10-05,MACHINE_OBSERVATION,1,CC_BY_4_0
2,5890686142,Ocelot,Leopardus pardalis,CO,5.274290,-71.439790,2.0,2025,10,2025-10-09,MACHINE_OBSERVATION,1,CC_BY_4_0
3,5890686813,Ocelot,Leopardus pardalis,CO,5.258392,-71.364642,2.0,2025,10,2025-10-05,MACHINE_OBSERVATION,1,CC_BY_4_0
4,5890685430,Ocelot,Leopardus pardalis,CO,5.277341,-71.371847,2.0,2025,10,2025-10-05,MACHINE_OBSERVATION,2,CC_BY_4_0

После всех преобразований полезно ещё раз вызвать <code>info()</code> и <code>head()</code>. Так видно итоговый размер таблицы, отсутствие пропусков в обработанных полях и то, что строки действительно идут от новых наблюдений к более старым.

<h2>4. Выбор целевой переменной</h2>

В качестве целевой переменной берём категориальный признак <code>common_name</code> — обычное название вида.

<b>Смысл признака.</b>  
Это метка вида: European Wildcat, Lion, Ocelot, Eurasian Lynx и т.д. Значений немного (около полутора десятков), все они текстовые — классическая категориальная переменная.

<b>Почему не подходят другие столбцы.</b>
<ul>
<li><code>gbif_id</code> — чистый идентификатор. Новый id не несёт информации о виде, поэтому для обучения модели он бесполезен.</li>
<li><code>scientific_name</code> по сути дублирует <code>common_name</code> на латыни. Для интерпретации удобнее привычные английские названия.</li>
<li><code>country_code</code> и <code>license</code> — тоже категории, но отвечают на вопросы «где» и «под какой лицензией», а не «какой вид наблюдали».</li>
<li><code>basis_of_record</code> описывает способ сбора (человек / датчик / образец), а не объект наблюдения.</li>
<li>Числовые поля (<code>year</code>, координаты, число особей) логичнее использовать как входные признаки, а не как класс.</li>
</ul>

<b>Какую задачу это задаёт.</b>  
Если <code>common_name</code> считать целью, дальше можно ставить задачу многоклассовой классификации: по стране, координатам, году, типу записи и лицензии пытаться отличить, например, льва от рыси или оцелота от дикой кошки.

<b>Ограничение.</b>  
Классы несбалансированы: European Wildcat встречается заметно чаще остальных. При построении модели это нужно будет учитывать, но для этапа разведочного анализа выбор вида как целевой переменной остаётся наиболее естественным.

<h2>5. Сохранение датасета</h2>

In [ ]:
output_path = "pw1_data_set_cleaned.csv"
df.to_csv(output_path, index=False)
print("Очищенный датасет сохранён в файл:", output_path)
print("Итоговые размерности:", df.shape)

<code>df.to_csv(path, index=False)</code> записывает текущую таблицу в новый файл.

<ul>
<li><code>path</code> - имя файла; берём другое имя, чтобы не затереть исходник;</li>
<li><code>index=False</code> - не сохранять служебный индекс pandas как отдельный столбец.</li>
</ul>

В очищенный CSV попадает версия без <code>dataset_key</code>, с заполненными пропусками, без самых слабых строк, без дубликатов и отсортированная от новых наблюдений к старым.

<h2><b>Вывод</b></h2>

В работе проведён разведочный анализ выборки наблюдений диких кошачьих из базы GBIF.

На этапе загрузки и исследования таблица прочитана через <code>read_csv</code> и изучена методами <code>info</code>, <code>head</code>/<code>tail</code>, <code>shape</code>, <code>dtypes</code>, <code>describe</code>, <code>isna</code>, <code>nunique</code> и <code>value_counts</code>. Исходный файл содержит 424 записи и 14 признаков. Данные охватывают 17 видов, 20 стран и период с 2000 по 2025 год. Пропуски сосредоточены в точности координат, числе особей и месяце. Столбец <code>dataset_key</code> оказался чисто техническим.

При обработке служебный <code>dataset_key</code> удалён. Пропуски в <code>month</code>, <code>individual_count</code> и <code>coordinate_uncertainty_m</code> заполнены осмысленными заглушками (0 / 1 / −1). Строки с большой пространственной неопределённостью и без месяца отфильтрованы. Таблица упорядочена по убыванию года и месяца, дубликаты проверены (их не оказалось).

Целевой переменной выбран <code>common_name</code> — обычное название вида, так как именно оно отражает объект наблюдения и подходит для задачи классификации.

Все требуемые этапы выполнены: загрузка, исследование, удаление признака, замена и удаление значений, сортировка, удаление дубликатов, обоснование целевой переменной, заключение и сохранение результата.